#!/usr/bin/env bash
# LearnOS — one-time privilege setup
# Run ONCE as root: sudo bash scripts/setup-permissions.sh
#
# What this does:
#   1. Stamps the current binary and all worker binaries with the Linux
#      capabilities they need (see annotated list below).
#   2. Writes a narrow passwordless sudoers rule so build.sh can re-stamp
#      after every rebuild without a password prompt.
#   3. Persists perf_event_paranoid=1 across reboots via /etc/sysctl.d/.
#   4. Mounts debugfs (for ftrace / EbpfLab) and makes the mount persistent.
#   5. Sets up the cgroup v2 hierarchy for sandbox isolation.
#
# This is the canonical capability-stamping script.
# install.sh delegates to this script — do not duplicate capability lists there.
set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
BUILD_DIR="$REPO/build"
BINARY="$BUILD_DIR/LearnOS"
SETCAP=/usr/sbin/setcap
USER="${SUDO_USER:-$(logname 2>/dev/null || echo "$USER")}"
SUDOERS_FILE="/etc/sudoers.d/learnos-setcap"

# ── 0. Must be root ──────────────────────────────────────────────────────────
if [ "$(id -u)" != "0" ]; then
    echo "ERROR: Run as root: sudo bash scripts/setup-permissions.sh"
    exit 1
fi

# ── 1. Build if binary is missing ────────────────────────────────────────────
if [ ! -f "$BINARY" ]; then
    echo "==> Binary not found — building first..."
    mkdir -p "$BUILD_DIR" && cd "$BUILD_DIR"
    cmake .. -DCMAKE_BUILD_TYPE=Release
    make -j"$(nproc)"
    cd "$REPO"
fi

# ── 2. Install libcap2-bin if needed ─────────────────────────────────────────
if ! command -v "$SETCAP" &>/dev/null && ! command -v setcap &>/dev/null; then
    echo "==> Installing libcap2-bin..."
    apt-get install -y libcap2-bin
fi
SETCAP="$(command -v setcap)"

# ── 3. Capability set (annotated) ────────────────────────────────────────────
#
#  cap_sys_nice    setpriority() on any PID; sched_setattr() — Process Viewer,
#                  Scheduler Lab
#  cap_sys_admin   /proc/sys writes; unshare(); cgroup v2; perf_event_open
#                  system-wide; read /proc/[pid]/pagemap (Phase 2 Page Table
#                  Inspector) — Namespace Lab, Memory Lab Phase 2, EbpfLab
#  cap_sys_ptrace  ptrace() / reading /proc/[pid]/mem; used by MemoryInspector
#                  to read the worker's address space details
#  cap_net_admin   Network namespace; tc (traffic control) — Namespace Lab
#  cap_ipc_lock    mlock() large regions without limits — Memory Lab stress tests
#  cap_kill        send signals to processes owned by other users — Signal Panel
#
# cap_perfmon is the fine-grained perf capability added in kernel 5.8.
# We try to set it but silently skip on older kernels where it doesn't exist.
#
CAPS_BASE="cap_sys_nice,cap_sys_admin,cap_sys_ptrace,cap_net_admin,cap_ipc_lock,cap_kill"
CAPS_FULL="${CAPS_BASE},cap_perfmon"

echo "==> Stamping capabilities on LearnOS binaries..."

stamp_binary() {
    local bin="$1"
    if [ ! -f "$bin" ]; then
        echo "    SKIP (not found): $bin"
        return
    fi
    # Try full set first (includes cap_perfmon); fall back to base set on
    # older kernels that don't recognise cap_perfmon.
    if "$SETCAP" "${CAPS_FULL}+ep" "$bin" 2>/dev/null; then
        echo "    OK (full set):  $bin"
    else
        "$SETCAP" "${CAPS_BASE}+ep" "$bin"
        echo "    OK (base set):  $bin"
    fi
}

stamp_binary "$BINARY"
stamp_binary "$BUILD_DIR/memlab_worker"
stamp_binary "$BUILD_DIR/dslab_worker"
stamp_binary "$BUILD_DIR/learnos_thread_worker"
stamp_binary "$BUILD_DIR/sched_worker"
stamp_binary "$BUILD_DIR/fslab_worker"

echo ""
getcap "$BINARY" || true

# ── 4. Passwordless sudoers rule for re-stamping after rebuilds ──────────────
echo "==> Writing passwordless sudoers rule for $USER..."
WRAPPER="$REPO/scripts/setcap-learnos.sh"
cat > "$WRAPPER" <<WRAP
#!/bin/bash
# Auto-generated by setup-permissions.sh — do not edit manually.
SETCAP="\$(command -v setcap)"
CAPS_BASE="cap_sys_nice,cap_sys_admin,cap_sys_ptrace,cap_net_admin,cap_ipc_lock,cap_kill"
CAPS_FULL="\${CAPS_BASE},cap_perfmon"
BUILD_DIR="$BUILD_DIR"
for bin in "\$BUILD_DIR/LearnOS" "\$BUILD_DIR/memlab_worker" "\$BUILD_DIR/dslab_worker" \
           "\$BUILD_DIR/learnos_thread_worker" "\$BUILD_DIR/sched_worker" \
           "\$BUILD_DIR/fslab_worker"; do
    [ -f "\$bin" ] || continue
    "\$SETCAP" "\${CAPS_FULL}+ep" "\$bin" 2>/dev/null || "\$SETCAP" "\${CAPS_BASE}+ep" "\$bin"
done
WRAP
chmod 0755 "$WRAPPER"

cat > "$SUDOERS_FILE" <<EOF
# Allow $USER to re-stamp LearnOS capabilities after each rebuild — no password.
# Scoped to the wrapper script only.
$USER ALL=(root) NOPASSWD: $WRAPPER
EOF
chmod 0440 "$SUDOERS_FILE"
visudo -c -f "$SUDOERS_FILE" && echo "   Syntax OK — $SUDOERS_FILE"

# ── 5. perf_event_paranoid ───────────────────────────────────────────────────
echo "==> Persisting perf_event_paranoid=1..."
echo "kernel.perf_event_paranoid = 1" > /etc/sysctl.d/60-learnos.conf
sysctl -w kernel.perf_event_paranoid=1

# ── 6. debugfs (for ftrace / EbpfLab) ───────────────────────────────────────
echo "==> Checking debugfs..."
if ! mountpoint -q /sys/kernel/debug 2>/dev/null; then
    mount -t debugfs none /sys/kernel/debug
    if ! grep -q "debugfs" /etc/fstab; then
        echo "none /sys/kernel/debug debugfs defaults 0 0" >> /etc/fstab
        echo "   Added debugfs to /etc/fstab"
    fi
fi
echo 1 > /sys/kernel/debug/tracing/tracing_on 2>/dev/null || true
echo "   debugfs ready, ftrace enabled"

# ── 7. cgroup v2 ────────────────────────────────────────────────────────────
echo "==> Setting up cgroup v2..."
if ! mountpoint -q /sys/fs/cgroup 2>/dev/null; then
    mount -t cgroup2 none /sys/fs/cgroup
fi
mkdir -p /sys/fs/cgroup/learnos
for ctrl in cpu memory pids; do
    if grep -q "$ctrl" /sys/fs/cgroup/cgroup.controllers 2>/dev/null; then
        echo "+$ctrl" > /sys/fs/cgroup/cgroup.subtree_control 2>/dev/null || true
    fi
done
chmod 777 /sys/fs/cgroup/learnos 2>/dev/null || true
echo "   cgroup v2 ready at /sys/fs/cgroup/learnos"

# ── Summary ──────────────────────────────────────────────────────────────────
echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║            LearnOS — Setup Complete                  ║"
echo "╚══════════════════════════════════════════════════════╝"
echo ""
echo "  Binary:  $BINARY"
echo "  Run:     $BINARY   (no sudo needed)"
echo ""
echo "  After each rebuild, re-stamp capabilities with:"
echo "  sudo $WRAPPER"
echo "  (or add a post-build step in build.sh — passwordless for $USER)"
echo ""
echo "  Capabilities granted:"
echo "  ✓ cap_sys_nice    — setpriority() any PID"
echo "  ✓ cap_sys_admin   — /proc/sys, unshare(), pagemap, perf system-wide"
echo "  ✓ cap_sys_ptrace  — /proc/[pid]/mem, process inspection"
echo "  ✓ cap_net_admin   — network namespaces"
echo "  ✓ cap_ipc_lock    — mlock() large regions"
echo "  ✓ cap_kill        — signals to any-user processes"
echo "  ✓ cap_perfmon     — hardware PMU counters (kernel >= 5.8, best-effort)"
echo ""
